
[t70]
price       = 0
attack      = 2
defense     = 2
icon        = res://cards/t-70.png
name        = t70
rarity      = common
cardType    = Tank
description =
effect      =
isHq        = 0
targetType  = NOTarget
traits      = Guardian

[su85]
price       = 4
attack      = 5
defense     = 3
icon        = res://cards/su85.png
name        = Su - 85
rarity      = common
cardType    = Tank
description = 友方坦克攻击时, 使友方总部获得3点防御力
effect      = FriendlyUnitAttacking:GetTargetByIndex(1)|if(target.cardType!=Tank)Jump|myHq|Heal(3)|Jump&[icon=action,description=友方坦克攻击时使总部回复3点防御力]
isHq        = 0
targetType  = NOTarget
traits      = Guardian

[i16]
price       = 1
attack      = 0
defense     = 1
icon        = res://cards/16.png
name        = 步兵第16团
rarity      = common
cardType    = Infantry
description = 友方回合开始时, 获得+1+1
effect      = FriendlyTurnBegin:this|Heal(1)|GetAttack(1)[icon=action,description=友方回合开始时获得+1攻击力和+1防御力]
isHq        = 0
targetType  = NOTarget
traits      = SmokeScreen

[i18]
price       = 1
attack      = 1
defense     = 1
icon        = res://cards/16.png
name        = 步兵第16团
rarity      = common
cardType    = Infantry
description = 部署:选择一个敌方单位,对其造成1点伤害
effect      = setTarget|damage(1)[icon=action,description=部署时对一个敌方单位造成1点伤害]
isHq        = 0
targetType  = anEnemyUnit
traits      = 

[喀秋莎]
price       = 1
attack      = 1
defense     = 1
icon        = res://cards/喀秋莎.png
name        = 喀秋莎
rarity      = common
cardType    = Artillery
description = 攻击时,获得1指挥点
effect      = Attacking:AddPoint(1)[icon=action,description=攻击时获得1指挥点]
isHq        = 0
targetType  = NOTarget
traits      = Blitz


[smileBro]
price       = 4
attack      = 6
defense     = 6
icon        = res://cards/微笑哥.png
name        = 近卫步兵272团
rarity      = common
cardType    = Infantry
description = 亡计:将一辆IS-2加入支援阵线
effect      = Dead:addToSupportLine(is2)[icon=action,description=死亡时将一辆IS-2加入支援阵线]
isHq        = 0
targetType  = NOTarget
traits      = Guardian

[is2]
price       = 10
attack      = 8
defense     = 8
icon        = res://cards/is2.png
name        = IS-2
rarity      = common
cardType    = Tank
description =部署:将1辆IS-2加入支援阵线
effect      = Deployed:addToSupportLine(is2)[icon=action,description=部署时将一辆IS-2加入支援阵线]
isHq        = 0
targetType  = NOTarget
traits      = HeavyArmor
[moscow]
price       = 0
attack      = 0
defense     = 20
icon        = res://cards/HQ_moscow.png
name        = moscow
rarity      = common
cardType    = Infantry
description = 莫斯科是苏联的首都
isHq        = 1
effect      = 
targetType  = NOTarget
traits      =

[berlin]
price       = 0
attack      = 0
defense     = 40
icon        = res://cards/HQ_berlin.png
name        = BERLIN
rarity      = common
cardType    = Infantry
description = 柏林是德国的首都
isHq        = 1
effect      = 
targetType  = NOTarget
traits      =


[塔曼斯卡亚]
price       = 1
attack      = 0
defense     = 0
icon        = res://cards/塔曼斯卡亚.png
name        = 塔曼斯卡亚
rarity      = common
cardType    = Command
description = 友方总部获得3点防御力,额外获得1个指挥点槽
effect      = myHq|Heal(3)|AddPointMax(1)[icon=action,description=友方总部获得3点防御力并增加1指挥点上限]
isHq        = 0
targetType  = NOTarget
traits      =

[i554]
price       = 1
attack      = 2
defense     = 2
icon        = res://cards/步兵第554团.png
name        = 步兵第554团
rarity      = common
cardType    = Infantry
description =
effect      =
isHq        = 0
targetType  = NOTarget
traits      = Blitz

[i17]
price       = 3
attack      = 6
defense     = 6
icon        = res://cards/步兵第17团.png
name        = 步兵第17团
rarity      = common
cardType    = Infantry
description = 被攻击时,回复1点防御力
effect      = BeingAttacked:this|Heal(1)[icon=action,description=被攻击时回复1点防御力]
isHq        = 0
targetType  = NOTarget
traits      =

[以剑之名]
price       = 3
attack      = 0
defense     = 0
icon        = res://cards/以剑之名.png
name        = 以剑之名
rarity      = common
cardType    = Command
description = 抽取3张卡
effect      = setResult(3)|drawCard[icon=action,description=抽取3张卡]
isHq        = 0
targetType  = NOTarget
traits      =

[拖拉机厂]
price       = 8
attack      = 0
defense     = 0
icon        = res://cards/拖拉机厂.png
name        = 拖拉机厂
rarity      = common
cardType    = Command
description = 将两个T34 1942加入支援阵线
effect      = addToSupportLine(t34_1942), addToSupportLine(t34_1942)[icon=action,description=将两辆T-34 1942加入支援阵线]
isHq        = 0
targetType  = NOTarget
traits      =

[来自人民]
price       = 2
attack      = 0
defense     = 0
icon        = res://cards/来自人民.png
name        = 来自人民
rarity      = common
cardType    = Command
description = 随即开发一张场上的友方单位
effect      = GetAllFriendUnits|Develop[icon=action,description=随机开发一张友方单位]
isHq        = 0
#targetType  = anEnemyUnit
targetType  = NOTarget
traits      =


[北极护航队]
price       = 3
attack      = 0
defense     = 0
icon        = res://cards/北极护航队_r.png
name        = 北极护航队
rarity      = common
cardType    = Command
description = 抽2张单位
effect      = DrawUnitCards(2)[icon=action,description=抽2张单位卡]
isHq        = 0
targetType  = NOTarget
traits      =

[铁锤]
price       = 3
attack      = 0
defense     = 0
icon        = res://cards/铁锤.png
name        = 铁锤
rarity      = common
cardType    = Command
description = 对一个目标造成6点伤害
effect      = setTarget|damage(6)[icon=action,description=对一个目标造成6点伤害]
isHq        = 0
targetType  = enemyTarget
traits      =

[大规模攻击]
price       = 4
attack      = 0
defense     = 0
icon        = res://cards/大规模攻击.png
name        = 大规模攻击
rarity      = common
cardType    = Command
description = 对一个目标造成等同于友方单位数量的伤害
effect      = getCount(${allTargets.unit.friend})|setTarget|damage[icon=action,description=对一个目标造成等同于友方单位数量的伤害]
isHq        = 0
targetType  = enemyTarget
traits      =

[伟大的卫国战争]
price       = 6
attack      = 0
defense     = 0
icon        = res://cards/伟大的卫国战争_r.png
name        = 伟大的卫国战争
rarity      = common
cardType    = Command
description = 将双方总部血量设为12
effect      = myHq|SetDefence(12)|enemyHq|SetDefence(12)[icon=action,description=将双方总部血量设为12]
isHq        = 0
targetType  = NOTarget
traits      =

[冬季战争]
price       = 1
attack      = 0
defense     = 0
icon        = res://cards/冬季战争_r.png
name        = 冬季战争
rarity      = common
cardType    = Command
description = 对所有目标造成1点伤害
effect      = GetAllEnemyTargets|damage(1)|GetAllFriendTargets|damage(1)[icon=action,description=对所有目标造成1点伤害]
isHq        = 0
targetType  = NOTarget
traits      =

[i97]
price       = 1
attack      = 1
defense     = 2
icon        = res://cards/97.png
name        = 步兵第97团
rarity      = common
cardType    = Infantry
description = 亡计:将一张步兵第414团洗入卡组
effect      = Dead:addToDeck(i414)[icon=action,description=死亡时将步兵第414团洗入卡组]
targetType  = NOTarget
traits      = 
#还没做完

[i414]
price       = 2
attack      = 5
defense     = 5
icon        = res://cards/伪人哥_r.png
name        = 步兵第414团
rarity      = Unobtainable
cardType    = Infantry
description = 亡计:将一张步兵第97团洗入卡组.对友方总部造成3点伤害,抽3张牌
effect      = Dead:addToDeck(i97)|myHq|damage(3)|setResult(3)|drawCard[icon=action,description=死亡时对友方总部造成3点伤害并抽3张牌]
targetType  = NOTarget
traits      = 

[t34_1942]
price       = 4
attack      = 5
defense     = 5
icon        = res://cards/t34_1942_h.png
name        = T-34 1942
rarity      = common
cardType    = Tank
description =
effect      =
isHq        = 0
targetType  = NOTarget
traits      = Blitz

[t34_85_1944]
price       = 7
attack      = 7
defense     = 7
icon        = res://cards/T-34-85 1944_c.png
name        = T-34-85 1944
rarity      = common
cardType    = Tank
description = 部署:若友方单位数不小于3,获得闪击和守护
effect      = Deployed:getCount(${allTargets.unit.friend})|this|if(result<4)Jump|Refresh|AddTrait(HeavyArmor)|Jump&[icon=action,description=部署时若友方单位数不少于3获得闪击和守护]
isHq        = 0
targetType  = NOTarget
traits      = HeavyArmor


[i12]
price       = 1
attack      = 2
defense     = 1
icon        = res://cards/121.png
name        = 近卫机械化第12旅
rarity      = common
cardType    = Infantry
description = 友方攻击不小于4的坦克部署时,抽2张卡
effect      = FriendlyTankDeployed:if(target.attack<4)Jump|setResult(2)|drawCard|Jump&[icon=action,description=攻击力不小于4的友方坦克部署时抽2张卡]
isHq        = 0
targetType  = NOTarget
traits      = Blitz


[毛驴]
price       = 2
attack      = 2
defense     = 2
icon        = res://cards/毛驴_r.png
name        = 毛驴
rarity      = common
cardType    = Plane
description =
effect      =
isHq        = 0
targetType  = NOTarget
traits      = SmokeScreen

[雅克7]
price       = 2
attack      = 2
defense     = 2
icon        = res://cards/雅克7.png
name        = 雅克7
rarity      = common
cardType    = Plane
description = 友方回合开始时,对友方总部造成1点伤害,抽1张牌
effect      = FriendlyTurnBegin:myHq|damage(1)|setResult(1)|drawCard[icon=action,description=友方回合开始时对总部造成1点伤害并抽1张牌]
isHq        = 0
targetType  = NOTarget
traits      = SmokeScreen

[强袭]
price       = 1
attack      = 0
defense     = 0
icon        = res://cards/强袭.png
name        = 强袭
rarity      = common
cardType    = Command
description = 对一个友方单位造成1点伤害,再对一个敌方单位造成4点伤害
effect      = setTarget|damage(1)|GetRandomEnemyUnit|damage(4)[icon=action,description=对一个友方单位造成1点伤害再对一个随机敌方单位造成4点伤害]
isHq        = 0
targetType  = aFriendlyUnit
traits      =

[血红的镰刀]
price       = 1
attack      = 0
defense     = 0
icon        = res://cards/血红的镰刀.png
name        = 血红的镰刀
rarity      = common
cardType    = Command
description = 对一个敌方单位造成1点伤害,对友方总部造成1点伤害,抽1张牌
effect      = setTarget|damage(1)|myHq|damage(1)|setResult(1)|drawCard[icon=action,description=对一个敌方单位造成1点伤害对总部造成1点伤害并抽1张牌]
isHq        = 0
targetType  = anEnemyUnit
traits      =

[轻步兵]
price       = 0
attack      = 1
defense     = 1
icon        = res://cards/轻步兵.png
name        = 轻步兵
rarity      = Unobtainable
cardType    = Infantry
description = 氢能源步兵
effect      = 
isHq        = 0
targetType  = NOTarget
traits      = 

[预备役]
price       = 1
attack      = 0
defense     = 0
icon        = res://cards/预备役.png
name        = 预备役
rarity      = common
cardType    = Command
description = 将2张轻步兵加入手中.每打出过一次预备役,再获得一张
effect      = SetMemory(prepare,&prepare+1)|AddToHand(轻步兵,&prepare+1)[icon=action,description=将轻步兵加入手中每打出过一次多获得一张]
isHq        = 0
targetType  = NOTarget
traits      =

[最后一击]
price       = 1
attack      = 0
defense     = 0
icon        = res://cards/最后一击.png
name        = 最后一击
rarity      = common
cardType    = Command
description = 使1个单位获得+3攻击力,下个友方回合开始时,消灭之
effect      = setTarget|GetAttack(3)|GetEffect("FriendlyTurnBegin:this|KillAllTargets[icon=action,description=回合开始时消灭自身]")[icon=action,description=使一个单位获得+3攻击力下回合开始时消灭]
isHq        = 0
targetType  = aFriendlyUnit
traits      =

[大纵深作战]
price       = 4
attack      = 0
defense     = 0
icon        = res://cards/大纵深作战.png
name        = 大纵深作战
rarity      = common
cardType    = Command
description = 将2张轻步兵加入支援阵线.友方所有轻步兵可再次行动
effect      = addToSupportLine(轻步兵)|addToSupportLine(轻步兵)|GetAllFriendUnits|foreach|if(target.name!=轻步兵)Jump|Refresh|Jump&|End&[icon=action,description=将2张轻步兵加入支援阵线并刷新所有友方轻步兵]
isHq        = 0
targetType  = NOTarget
traits      =

[正面突击]
price       = 2
attack      = 0
defense     = 0
icon        = res://cards/正面突击.png
name        = 正面突击
rarity      = common
cardType    = Command
description = 使所有友方轻步兵获得+1+2,若友方场上没有轻步兵,将2张轻步兵加入手中
effect      = setResult(0)|GetAllFriendUnits|foreach|if(target.name!=轻步兵)Jump|GetAttack(1)|Heal(2)|setResult(1)|Jump&|End&|if(result>0)A|AddToHand(轻步兵,2)|A&[icon=action,description=所有友方轻步兵获得+1+2若无则加入手牌]
isHq        = 0
targetType  = NOTarget
traits      =

[装甲列车]
price       = 5
attack      = 5
defense      = 5
icon        = res://cards/装甲列车_r.png
name        = 装甲列车
rarity      = common
cardType    = Tank
description = 友方回合开始时,将一个轻步兵加入支援阵线
effect      = FriendlyTurnBegin:addToSupportLine(轻步兵)[icon=action,description=友方回合开始时将一个轻步兵加入支援阵线]
isHq        = 0
targetType  = NOTarget
traits      = HeavyArmor,Guardian

[机动防御]
price       = 3
attack      = 0
defense      = 0
icon        = res://cards/机动防御.png
name        = 机动防御
rarity      = common
cardType    = Command
description = 将2个t70加入支援阵线,下个友方回合开始时,将其消灭
effect      = addToSupportLine(t70_机动防御)|addToSupportLine(t70_机动防御)[icon=action,description=将2个t70加入支援阵线]
isHq        = 0
targetType  = NOTarget
traits      = 

[t70_机动防御]
price       = 0
attack      = 2
defense     = 2
icon        = res://cards/t-70.png
name        = t70
rarity      = common
cardType    = Tank
description = 下个友方回合开始时,消灭自身
effect      = FriendlyTurnEnd:if(&lifeTime>0)Jump|this|KillAllTarget|Jump&[icon=action,description=下个友方回合结束时消灭自身]
isHq        = 0
targetType  = NOTarget
traits      = Guardian
